version: "3.8"

services: 
    web:
        env_file:
            - ./.env.prod
        build:
            context: ./services/web
            dockerfile: Dockerfile.prod
        command: gunicorn --worker-class gthread --workers ${WORKERS} --bind 0.0.0.0:5000 "wsgi:application"
        expose:
            - 5000
        depends_on:
            - db

    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db


    nginx:
        build: ./services/nginx
        ports:
            - 1337:80
        depends_on:
            - web

volumes:
    postgres_data:
