version: "3.8"

services:
    web:
        build: ./services/web
        command: >-
            gunicorn --worker-class gthread --workers ${WORKERS}
                     --bind 0.0.0.0:5000 wsgi:app
                     --access-logfile /home/flasker/web/logs/gunicorn-access.log
                     --error-logfile /home/flasker/web/logs/gunicorn-error.log

        volumes:
            - static_volume_1:/home/flasker/web/flaskr/auth/static
            - static_volume_2:/home/flasker/web/flaskr/blog/static
        expose:
            - 5000
        env_file:
            - ./.env.prod
        depends_on:
            - db

    db:
        image: postgres:12-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./.env.prod.db

    nginx:
        build: ./services/nginx
        volumes:
            - static_volume_1:/home/flasker/web/flaskr/auth/static
            - static_volume_2:/home/flasker/web/flaskr/blog/static
        ports:
            - 1337:80
        depends_on:
            - web

volumes:
    postgres_data:
    static_volume_1:
    static_volume_2:
