#! /usr/bin/bash

while getopts "n:" arg; do
    case "$arg" in
      n) ntw_name="$OPTARG" ;;
      *) ntw_name= ;;
    esac
  done
  shift $((OPTIND - 1))
  action=$1

if [[ -z "$action" || -z "$ntw_name" ]] ; then
   echo "Missing parameter(s)"
   exit 1
fi
set -x
if [ $action = "up" ] ; then
  podman network create $ntw_name
  podman create -d --env-file ./.env.db --network $ntw_name -v postgres_data:/var/lib/postgresql/data/ --hostname db --name flaskr_db postgres:12-alpine
  podman create --env-file .env.prod --network $ntw_name --expose 5000 -v static_volume_1:/home/flasker/web/flaskr/auth/static -v static_volume_2:/home/flasker/web/flaskr/blog/static -d --hostname web --name flaskr_web flaskr_web
  podman create --network $ntw_name -p 1337:80 -v static_volume_1:/home/flasker/web/flaskr/auth/static -v static_volume_2:/home/flasker/web/flaskr/blog/static -d --hostname nginx --name flaskr_nginx flaskr_nginx
  exit 0
fi

if [ $action = "down" ] ; then
  podman container stop flaskr_nginx flaskr_web flaskr_db
  podman container rm flaskr_nginx flaskr_web flaskr_db
  podman network rm $ntw_name
  exit 0
fi

echo "Unknown action"
exit 1
