#! /usr/bin/bash

while getopts "p:" arg; do
    case "$arg" in
      p) pod_name="$OPTARG" ;;
      *) pod_name= ;;
    esac
  done
  shift $((OPTIND - 1))
  action=$1

if [[ -z "$action" || -z "$pod_name" ]] ; then
   echo "Missing parameter(s)"
   exit 1
fi
set -x
if [ $action = "up" ] ; then
  podman pod create --name $pod_name -p 1337:80
  podman create -d --env-file ./.env.db --pod $pod_name -v postgres_data:/var/lib/postgresql/data/ --name flaskr_db postgres:12-alpine
  podman create --env-file .env.dev --pod $pod_name -v static_volume_1:/home/flasker/web/flaskr/auth/static -v static_volume_2:/home/flasker/web/flaskr/blog/static -d --name flaskr_web flaskr_web
podman create --pod $pod_name -v static_volume_1:/home/flasker/web/flaskr/auth/static -v static_volume_2:/home/flasker/web/flaskr/blog/static -d --name flaskr_nginx flaskr_nginx
  podman pod start $pod_name
  exit 0
fi

if [ $action = "down" ] ; then
  podman pod stop $pod_name
  podman pod rm $pod_name
  exit 0
fi

echo "Unknown action"
exit 1
