#!/usr/bin/env bash

set -o errexit

container=$(buildah from nginx:1.18-alpine)

container_mp=$(buildah mount $container)

buildah run $container rm /etc/nginx/conf.d/default.conf
buildah run $container mkdir -p /var/log/nginx/flaskr
cp nginx.conf $container_mp/etc/nginx
cp flaskr.conf $container_mp/etc/nginx/conf.d

buildah unmount $container

buildah commit --rm $container  flaskr_nginx:1.1

